name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
exclude-labels:
    - 'duplicate'
    - 'invalid'
    - 'wontfix'
exclude-contributors:
    - 'dependabot'
    - 'weblate'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&`#@'
version-resolver:
    minor:
        labels:
            - 'feature request'
            - 'release'
            - 'technical debt'
            - 'bug'
            - 'translation'
    default: minor
template: |
    **Compatible with PHP 8.2 to 8.5**
    
    $CHANGES
    
    **Security**
    
    - This release contains a fix for a high severity security issue reported by @shafiqaimanx
    
    You can read more about all published vulnerabilities [here](https://www.kimai.org/documentation/bughunter.html#published-vulnerabilities) or grab a [RSS feed](https://www.kimai.org/security.xml) to get notified about new published advisories.

    Involved in this release: $CONTRIBUTORS
