parameters:
    env(MESSENGER_TRANSPORT_DSN): 'doctrine://default?auto_setup=0'

framework:
    messenger:
        failure_transport: failed

        transports:
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed

            failed_emails:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed_emails

            emails:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: emails
                failure_transport: failed_emails
                retry_strategy:
                    max_retries: 5
                    multiplier: 2
                    delay: 60000
                    max_delay: 0

            failed_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed_async

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: async
                failure_transport: failed_async
                retry_strategy:
                    max_retries: 5
                    multiplier: 2
                    delay: 60000
                    max_delay: 0

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': emails
            'App\Jobs\Event\*': async
            'App\Jobs\AsyncMessage': async

when@test:
    parameters:
        env(MESSENGER_TRANSPORT_DSN): 'in-memory://'
