framework:
    rate_limiter:
        session_prediction:
            policy: 'fixed_window'
            limit: 250
            interval: '1 hour'
            lock_factory: null
        reset_password:
            policy: 'fixed_window'
            limit: 10
            interval: '6 hours'
            lock_factory: null
