build:
    environment:
        node: v8.11.2
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
                    - php-scrutinizer-run
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=clover.xml tests/'
                        coverage:
                            file: 'clover.xml'
                            format: 'clover'
                    -
                        command: 'bin/console kimai:phpcs --checkstyle=checkstyle'
                        analysis:
                            file: 'checkstyle'
                            format: 'php-cs-checkstyle'

filter:
    excluded_paths:
        - '.github/'
        - 'bin/'
        - 'config/'
        - 'public/'
        - 'templates/'
        - 'translations/'
        - 'var/'
    dependency_paths:
        - 'node_modules/'
        - 'vendor/'
