volumes:
    db-dev:

services:
    db-dev:
        image: mariadb:lts
        environment:
            - MARIADB_DATABASE=kimai
            - MARIADB_USER=kimai
            - MARIADB_PASSWORD=kimai
            - MARIADB_RANDOM_ROOT_PASSWORD=1
        volumes:
            - db-dev:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

    kimai-dev:
        image: thecodingmachine/php:8.2-v4-apache
        environment:
            - PHP_EXTENSIONS=xdebug gd intl
            - PHP_INI_MEMORY_LIMIT:=1g
            - APACHE_DOCUMENT_ROOT=public/
            - STARTUP_COMMAND_1=composer install

            - APP_ENV=dev
            - DATABASE_URL=mysql://kimai:kimai@db-dev:3306/kimai?charset=utf8&serverVersion=5.7
        volumes:
            - ./:/var/www/html
        depends_on:
            db-dev:
                condition: service_healthy
        expose:
            - 80