name: Bug report
description: Create a report to help us improve Kimai
labels: [ "bug" ]
body:
    -   type: markdown
        attributes:
            value: |
                Thank you for reporting an issue on Kimai! This form will guide you to create a useful issue report.
    -   type: textarea
        id: what-happened
        attributes:
            label: Describe the issue
            description: A clear and concise description of the problem you are facing.
            placeholder: Tell us what you see!
        validations:
            required: true
    -   type: checkboxes
        id: tried
        attributes:
            label: I already tried
            description: If you didn’t try already, try to search the documentation and existing issues what you wrote above.
            options:
                -   label: I've read and searched [the documentation](https://www.kimai.org/documentation/).
                    required: true
                -   label: I've searched for similar issues in this repository.
                    required: true
                -   label: I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).
                    required: true
    -   type: input
        id: version
        attributes:
            label: Kimai version
            description: Which version of Kimai are you running (check Doctor or About screen)
            placeholder: 1.xx.x
        validations:
            required: true
    -   type: dropdown
        id: php
        attributes:
            label: Which PHP version are you using?
            options:
                - "7.3"
                - "7.4"
                - "8.0"
                - "8.1"
                - "8.2"
                - Other (please mention below)
        validations:
            required: true
    -   type: dropdown
        id: installation
        attributes:
            label: How do you run Kimai?
            options:
                - kimai.cloud service
                - Self-Hosted
                - Synology
                - Other (please mention below)
        validations:
            required: true
    -   type: textarea
        id: reproducer
        attributes:
            label: Steps to reproduce the behavior
            value: |
                1. Go to '...'
                2. Scroll down to '...'
                3. Click on '...'
                4. See error
    -   type: textarea
        id: logs
        attributes:
            label: Logfile
            description: Please paste the last lines from your logfile at "var/log/prod.log" or "Doctor > Logs", around the time when the problem happened.
    -   type: textarea
        id: screenshots
        attributes:
            label: Screenshots
            description: If applicable, add screenshots to better explain your problem.
    -   type: textarea
        id: additional
        attributes:
            label: Additional context
            description: Add any other context about the problem here.
            value: |
                Device: [Ubuntu Laptop 16 inch, Windows Desktop 27 inch, iPhone 6s]
                Browser [e.g. Firefox 81, Chrome 85, Safari 14]
