[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700
username=admin
password=kimai-supervisor

[supervisord]
nodaemon=true
user=root
logfile=/dev/stderr
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
username=admin
password=kimai-supervisor

[program:apache]
command=/usr/sbin/apache2 -D FOREGROUND
autostart=true
autorestart=true
stopsignal=WINCH
stopwaitsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:messenger-worker]
command=/opt/kimai/bin/console messenger:consume async emails --time-limit=3600 --memory-limit=128M --keepalive -v
autostart=true
autorestart=true
startsecs=5
stopsignal=TERM
stopwaitsecs=10
user=%(ENV_APACHE_RUN_USER)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20
