name: Frontend
on:
    pull_request: null
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions: {}

jobs:
    frontend:
        runs-on: ubuntu-latest
        name: Frontend verification
        steps:
            - name: Clone Kimai
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false

            - name: Setup PNPM
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
              with:
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24
                  cache: pnpm
                  cache-dependency-path: pnpm-lock.yaml

            - name: Install frontend dependencies
              run: pnpm install --frozen-lockfile --ignore-scripts

            - name: Check for security issues in frontend dependencies
              run: pnpm audit
