name: Renovate

permissions: {}

on:
    schedule:
        - cron: '17 3 * * *'
    workflow_dispatch:

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Kimai
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Run Renovate
              uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
              with:
                  configurationFile: .github/renovate-config.js
                  token: ${{ secrets.RENOVATE_TOKEN }}
